{% set name = "pytest-testmon" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8810f991545e352f646fb382e5962ff54b8aa52b09d62d35ae04f0d7a9c58d9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pytest >=2.8.0,<4
    - coverage >=4

test:
  imports:
    - testmon

about:
  home: https://github.com/tarpas/pytest-testmon/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: When re-running a test suite, skip re-running of tests if code affecting those tests has not changed.
  description: This is a py.test plug-in which automatically selects and re-executes only tests affected by recent changes.
  doc_url: https://pypi.python.org/pypi/pytest-testmon
  dev_url: https://github.com/tarpas/pytest-testmon/

extra:
  recipe-maintainers:
    - notestaff
