travis:
  secure:
    BINSTAR_TOKEN: DcnJHb41dlD3ziq06Q7HyA1cyQ5zZyQmFo3j1j4pnbQmPDIJvI7Hxy8n1LNQkRv3TxZlH8XZX0V/Dcn2E2UtP/fLubYUpqe/KhNbHrfKbw3/KQzCOe6WD8yayKhJ6FQPgX0JtngMuMVJP/wFEzC1Mt482hPCiAFSL4SZmPDfHmW6a1VlRgIe/OjKCpk6rOXMGNHnrZv1tOj76qmDzw+9sx/RgDuwxZb4a8Si0vn+eKodYUHVtr1NzU33Epm2QQM/MXhctvk2ok+M/WOdzYVWwKTGBufhP7Af9ekM2KYFHyIZrmIRh2qDUuA/vzfzMtTt39G/bmZLJt/WOfeigy9em4RVkIVvgOjyiiungQihKf+UUpraM95KII7x/gXHUWU2kXfBLIynhIeLkZbgZAKf//L1nJ/K2BvdLMtIy9JEZB0cCGNV7Zs1bzNg6S1KZrYxfX0MoNXi5AMzFN7Eihe8zi8IVloa+oGzcS0HM42FzmsW9wkYCyLy1aBo8gPJ679DQ2o+bTmMX7aaqJKDfDHqBdenYS0ALSOB1hcd2zGBh5taWx9F5l+IlfX3YoSqNnubslVHEvusK/BrbCvTl4olfgum7sV7Yp4IxAE/uVpWycPBsXYKKL9AQABqLbvYhRVB1ZQOyRnJKlhtsVoMOAsHmPb1esndKalpyIbCr7cv+xk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
