travis:
  secure:
    BINSTAR_TOKEN: gQdYb5aD4Q2F8wCJ+7fmQDERZV5qgBlUhSlFZq6bUdKCgmgYxnk2UtsN/TnhhfLBlf7MvcM5TYzNmUPMvZyciU3w5Ij8jJ+pwYIeU2EFiVdFqRYb8JPu3/YuJVUPN6NGP3X7/GwEHVEPuU+/Jv6Hs9Pa0xqVN4rDUPxn9x6UTmoP/iFX5wujnJ+HXz4kWpB4DqZl0v9CFRy5Z1OCgpH7gBHlrNAuMdo0Y/A40GbkMRvNB5/lCU5z2L4GzgKqkf9yMmCH4gHfLyDYxlvHqH35uPThubOuatXePI94hfKg7Rq8B9V6hV4NWZubQj6tSJjvYbOA23AHCW7XNS9Gkyt5Zudq+usw6DloZRrOXl7TcbiXWj8AvE88lkKf0PLQWy0VOcW2NvlLx6bgSHM3UmKn6qGym7uYwZIxvRPO/sqrkYLHWWdfGFRPmUhcXC3hKAklrKZm7QQf9N7hSrUGV5NGr4wK1OCN8wmtOEVX6x7iD4MzYtmF7Jv0T8gKpWOEkswmI3w9vvJTKvKfKO58D8xEwjor2q2qeTAoKrhQU48O79coacQXfonypLhnPW6wi1AVUjkrgLfyan4rpitPpI6u3TDTvinCgsXyQF58gBSSYMS27UCwdhO6vzjtEDAo37PyWv0ef32U4UrIrWpiXzZ1LDvu8rHo8Fkau7/RrNkqyYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
