travis:
  secure:
    BINSTAR_TOKEN: NoYii4y4uXWcvNuiH8r7kzkiv9gns6QR4t51vUzAQXdqcOIPqlNWlF4WG0LPOnPTZR54v7n3vJ1/nuTUrEvJzXxMlW3Ul27TAUR+40rLWE7cHggQo1sIr+GyeNB+T47Hv3T6MeUaHA514COJeW3GTlbagap8z22iklhQGOe8ER613uHHCyjv6aURqQyg0Q0SAmv9pZ3+GHyEPC9+2ZM9qjTlkRspZNK3Ydfw9uE/XziIca7xZFdEFMdyTFgp1ktgxXtCpj3ETn4o+2Ao7TiJpC6li+KGvTjVgfYa7B9ui/UB0z75PjTmrlRRxBfBOAzmcjBU5bArYTDKp/fpjYfJAWUF3CeXwzDBRDseXv0MeP6hyTsPFksbBjd7uEtm4ZBYyH3Yos/OGM4TAKNAU10VifvDhwSSW/Jo9KzhGQkidfRy7RhivgFflg77eSW6wgU+7P5hX1HD7QTFt2pYyfud84Yptop3R68gewjLlCb7BCF352w/vSfXGs7v1IIm+6eD+MDYzj0tzUXqnvy5I5nS7noBxotqSswj6zq+UT1SAvl755TCqYfTxmxM89/BhJhoIhHFSzsx7U9CxzN9zLVBz1rp6AIqmpjjzpQtR50oim/fYOTTact5JlgXJ/EJ4O1f1e6TRin8TR9KeoM2kNA3AQmAEwMeG6xCQGwDPjHU1Q8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
